//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BankEntities : DbContext
    {
        public BankEntities()
            : base("name=BankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankAccount_> BankAccount_ { get; set; }
        public virtual DbSet<Contract_> Contract_ { get; set; }
        public virtual DbSet<History_> History_ { get; set; }
        public virtual DbSet<Passport_> Passport_ { get; set; }
        public virtual DbSet<Type_> Type_ { get; set; }
        public virtual DbSet<TypeOperation_> TypeOperation_ { get; set; }
        public virtual DbSet<User_> User_ { get; set; }
    }
}
